In [1]:
import numpy as np

**Create numpy array**

In [84]:
ls = [1,2,3,4]
a = np.array(ls)
a

array([1, 2, 3, 4])

## **Create a range of elements**

In [87]:
# Create a range of elements excluding the end
# np.arange(start,end,step)
b = np.arange(0,10,2)
b

array([0, 2, 4, 6, 8])

In [91]:
# np.linspace(start,end, #_of_elements)
# note: both start and end are inclusive
c = np.linspace(0,9,10, dtype='int')
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Create a random numpy array 

**Sets a seed for the generator**

In [99]:
np.random.seed(42)

In [97]:
# Uniform random => [0,1]
# np.random.rand(row,col)
np.random.rand(2,2)

array([[0.17768785, 0.96433793],
       [0.64397404, 0.61164817]])

In [96]:
# Normal random => [-1,1]
# np.random.randn(row,col)
np.random.randn(2,2)

array([[ 1.35116764,  1.99885781],
       [-0.37477682, -0.24527036]])

In [98]:
# Integer random => [start, end]
# np.random.randint(start,end, #_of_elements)
np.random.randint(0,100,10)

array([ 6, 38, 45, 48, 32, 69, 36, 41, 96, 61])

**Reshape a numpy array**

In [103]:
a = np.random.randint(0,100,25)
print(a.shape)
a

(25,)


array([ 3, 53, 92, 62, 17, 89, 43, 33, 73, 61, 99, 13, 94, 47, 14, 71, 77,
       86, 61, 39, 84, 79, 81, 52, 23])

In [104]:
# np.reshape(numpy_arr, size_to_reshape_to)
# size_to_reshape_to => (row,col)
# Note: setting row or col to -1, autoreshapes accordingly to either attribute
np.reshape(a,(5,-1))

array([[ 3, 53, 92, 62, 17],
       [89, 43, 33, 73, 61],
       [99, 13, 94, 47, 14],
       [71, 77, 86, 61, 39],
       [84, 79, 81, 52, 23]])

**Min and Max value of numpy array**

In [105]:
a.max()

99

In [106]:
a.min()

3

**Index of Min and Max value of numpy array**

In [107]:
a.argmax()

10

In [108]:
a.argmin()

0

In [111]:
# type of numpy array
a.dtype

dtype('int32')

**Numpy array broadcast**

In [117]:
a = np.random.randint(0,50,20)
a

array([25, 24, 44, 40, 28, 14, 44,  0, 24,  6,  8, 23,  0, 43,  7, 23, 10,
       16,  7, 34])

In [118]:
# Modifying segment of nparray a
slice_of_a = a[:6]
slice_of_a[:] = 0
slice_of_a

array([0, 0, 0, 0, 0, 0])

In [119]:
# Accessing original nparray
a

array([ 0,  0,  0,  0,  0,  0, 44,  0, 24,  6,  8, 23,  0, 43,  7, 23, 10,
       16,  7, 34])

**To prevent overriding of original array, use .copy()**

In [123]:
b = a.copy()
b

array([ 0,  0,  0,  0,  0,  0, 44,  0, 24,  6,  8, 23,  0, 43,  7, 23, 10,
       16,  7, 34])

In [124]:
b[:6] = 20
b

array([20, 20, 20, 20, 20, 20, 44,  0, 24,  6,  8, 23,  0, 43,  7, 23, 10,
       16,  7, 34])

In [125]:
a # Unchanged

array([ 0,  0,  0,  0,  0,  0, 44,  0, 24,  6,  8, 23,  0, 43,  7, 23, 10,
       16,  7, 34])

**Slicing nparray**

In [127]:
arr_2d = np.array(
    [
        [5,10,15],
        [20,25,30],
        [35,40,45]
    ]
)
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [128]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

**Filter nparray**

In [129]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
flag = arr > 4
flag

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [138]:
arr[flag]

array([5, 6, 7, 8, 9])

**Error handling by numpy**

In [142]:
arr/0

C:\Users\hyder\AppData\Local\Temp/ipykernel_7252/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0
C:\Users\hyder\AppData\Local\Temp/ipykernel_7252/4291252909.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [154]:
print(arr_2d)
print()
# axis = 0 : Sum across rows (top to bottom)
print(arr_2d.sum(axis=0))
print()
# axis = 1: Sum across columns (left to right)
print(arr_2d.sum(axis=1))

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]

[60 75 90]

[ 30  75 120]
