In [1]:
import numpy as np

## **Create numpy array**

In [2]:
ls = [1,2,3,4]
a = np.array(ls)
a

array([1, 2, 3, 4])

## **Element generator**

In [3]:
# Sequenced elements with steps
# Create a range of elements excluding the end
# np.arange(start,end,step)
b = np.arange(0,10,2)
b

array([0, 2, 4, 6, 8])

In [4]:
# Evenly spaced elements
# np.linspace(start,end, #_of_elements)
# note: both start and end are inclusive
c = np.linspace(0,9,10, dtype='int')
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Random Generator

**Sets a seed for the generator**
- Allows replicating results

In [5]:
np.random.seed(42)

In [6]:
# Uniform random => [0,1]
# np.random.rand(row,col)
np.random.rand(2,2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848]])

In [7]:
# Normal random => [-1,1]
# np.random.randn(row,col)
np.random.randn(2,2)

array([[-0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473]])

In [8]:
# Integer random => [start, end]
# np.random.randint(start,end, #_of_elements)
np.random.randint(0,100,10)

array([21, 52,  1, 87, 29, 37,  1, 63, 59, 20])

## **Reshape a numpy array**

In [9]:
a = np.random.randint(0,100,25)
print(a.shape)
a

(25,)


array([32, 75, 57, 21, 88, 48, 90, 58, 41, 91, 59, 79, 14, 61, 61, 46, 61,
       50, 54, 63,  2, 50,  6, 20, 72])

In [10]:
# np.reshape(numpy_arr, size_to_reshape_to)
# size_to_reshape_to => (row,col,...), number of elements in the tuple indicates the dimension of the nparray
# Note: setting row or col to -1, autoreshapes/infers accordingly to either attribute
# a.reshape(5,-1) # Same as this
np.reshape(a,(5,-1)) # here (5,-1) is of length 2, indicating a 2 dimensional aarray

array([[32, 75, 57, 21, 88],
       [48, 90, 58, 41, 91],
       [59, 79, 14, 61, 61],
       [46, 61, 50, 54, 63],
       [ 2, 50,  6, 20, 72]])

## **Min and Max value of numpy array**

In [11]:
a.max()

91

In [12]:
a.min()

2

## **Index of Min and Max value of numpy array**

In [13]:
a.argmax()

9

In [14]:
a.argmin()

20

In [15]:
# type of numpy array
a.dtype

dtype('int32')

## **nparray linkage**

In [16]:
a = np.random.randint(0,50,20)
a

array([38, 17,  3, 24, 13, 49,  8, 25,  1, 19, 27, 46,  6, 43,  7, 46, 34,
       13, 16, 35])

In [17]:
# Modifying segment of nparray a
slice_of_a = a[:6]
slice_of_a[:] = 0
slice_of_a

array([0, 0, 0, 0, 0, 0])

In [18]:
# Accessing original nparray
a

array([ 0,  0,  0,  0,  0,  0,  8, 25,  1, 19, 27, 46,  6, 43,  7, 46, 34,
       13, 16, 35])

## **Break linkage**
**To prevent overriding of original array, use ```.copy()```**

In [19]:
b = a.copy()
b

array([ 0,  0,  0,  0,  0,  0,  8, 25,  1, 19, 27, 46,  6, 43,  7, 46, 34,
       13, 16, 35])

In [20]:
b[:6] = 20
b

array([20, 20, 20, 20, 20, 20,  8, 25,  1, 19, 27, 46,  6, 43,  7, 46, 34,
       13, 16, 35])

In [21]:
a # Unchanged

array([ 0,  0,  0,  0,  0,  0,  8, 25,  1, 19, 27, 46,  6, 43,  7, 46, 34,
       13, 16, 35])

## **Slicing nparray**

In [22]:
arr_2d = np.array(
    [
        [5,10,15],
        [20,25,30],
        [35,40,45]
    ]
)
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

## **Filter nparray**

In [24]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
flag = arr > 4
flag

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [26]:
arr[flag]

array([5, 6, 7, 8, 9])

## **Error handling by numpy**

In [27]:
arr/0

C:\Users\hyder\AppData\Local\Temp/ipykernel_34052/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0
C:\Users\hyder\AppData\Local\Temp/ipykernel_34052/4291252909.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [28]:
print(arr_2d)
print()
# axis = 0 : Sum across rows (top to bottom)
print(arr_2d.sum(axis=0))
print()
# axis = 1: Sum across columns (left to right)
print(arr_2d.sum(axis=1))

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]

[60 75 90]

[ 30  75 120]
