In [1]:
import torch
import numpy as np
np.random.seed(42)

In [2]:
arr = np.random.randint(0,10,10)
arr

array([6, 3, 7, 4, 6, 9, 2, 6, 7, 4])

## **Convert numpy to tensor**
- Link is preserved to original nparray `arr`
- Applies to both: `.from_numpy()` and `.as_tensor()`

In [3]:
# torch.from_numpy(np_array)
t1 = torch.from_numpy(arr)
t1

tensor([6, 3, 7, 4, 6, 9, 2, 6, 7, 4], dtype=torch.int32)

In [4]:
# torch.as_tensor(np_array)
t1 = torch.as_tensor(arr)
t1

tensor([6, 3, 7, 4, 6, 9, 2, 6, 7, 4], dtype=torch.int32)

## 2D tensor

In [5]:
arr_2d = np.random.randint(0,10,12).reshape(4,-1)
t1_2d  = torch.tensor(arr_2d)
t1_2d

tensor([[3, 7, 7],
        [2, 5, 4],
        [1, 7, 5],
        [1, 4, 0]], dtype=torch.int32)

## **Copy**
Break link to original tensor, make a copy using
```torch.tensor()```

In [6]:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_tensor = torch.tensor(my_arr)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [8]:
my_other_tensor = torch.from_numpy(my_arr) # Actively shares memory with the original nparray
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [9]:
# Making changes to original nparray, reflects changes in copies and vice cersa
my_arr[0] = -1
my_other_tensor

tensor([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9], dtype=torch.int32)

In [10]:
# Making changes to copy of nparray, reflects changes back to original nparray
my_other_tensor[0] = 0
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
print(f"Original nparray: {my_arr}")
my_arr[0] = -1 # Making changes
print(f"Change to nparray: {my_arr}")
my_tensor # Copy of nparray as tensor, remains unaffected (No Linkage, Memory not shared)

Original nparray: [0 1 2 3 4 5 6 7 8 9]
Change to nparray: [-1  1  2  3  4  5  6  7  8  9]


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

## Difference in tensor and Tensor
Float Tensor => torch.Tensor() \
dynamic Tensor => torch.tensor()

*Note:* depends on the datatype of the original nparray passed as argument

In [12]:
my_arr = np.arange(0,1,0.1)
my_arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [13]:
torch.tensor(my_arr) # Infers the datatype of my_arr

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000], dtype=torch.float64)

In [14]:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# t = torch.FloatTensor(my_arr)
t = torch.Tensor(my_arr) # Converts to float
print(t)
print(t.dtype)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.float32


## Initialize empty tensors
Place holder tensors with extremely small floating values \
```torch.empty(ndim,...)```

In [16]:
torch.empty(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [17]:
# Placeholder tensors with zeros
torch.zeros(2,2, dtype=torch.int32)

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)

In [18]:
# Placeholder tensors with ones
torch.ones(2,2, dtype = torch.int32)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

## **Tensor generator**

In [19]:
# Sequence generated elements with steps
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# Evenly spaced elements
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

## Reshape
Use ```.reshape(size_to_reshape_to)```  
size_to_reshape_to => (n1,n2,...n) where the length of this tuple dictates the dimension of the tensor

In [21]:
torch.arange(0,10).reshape(5,-1) # (5,-1), len = 2, 2-dimensional array

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

## Modify dtype
Use ```.type(dtype)```

*Note:* dtype for torch objects are ```torch.<dtype>``` \
    where dtype = ['int32', 'int64', 'float32', ...]

In [49]:
my_tensor = torch.arange(0,5)
print(my_tensor)
my_tensor.dtype

tensor([0, 1, 2, 3, 4])


torch.int64

In [50]:
my_tensor.type(torch.int32)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)

In [51]:
my_tensor.dtype

torch.int64

## Random Generator

In [24]:
# Set the seed
torch.manual_seed(42)

In [25]:
# Uniform random => [0,1]
torch.rand(2,2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])

In [26]:
# Normal random => [-1,1]
torch.randn(2,2)

tensor([[ 0.2345,  0.2303],
        [-1.1229, -0.1863]])

In [27]:
# Integer random => [start, end]
# torch.randint(start,end, size)
# size => (rows,cols)
torch.randint(0,10,(5,4))

tensor([[0, 4, 1, 2],
        [5, 5, 7, 6],
        [9, 6, 3, 1],
        [9, 3, 1, 9],
        [7, 9, 2, 0]])

**Random Generator for a similar shaped tensor** \
Creates a random tensor that preserves the shape of the original tensor  
 ```torch.<r>_like()``` \
where `<r>` = ['rand', 'randn', ...]

In [28]:
my_tensor = torch.zeros(2,3)
my_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [29]:
# Uniform 
torch.rand_like(my_tensor)

tensor([[0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040]])

In [30]:
# Normal
torch.randn_like(my_tensor)

tensor([[-0.3639,  0.1513, -0.3514],
        [-0.7906, -0.0915,  0.2352]])

In [31]:
# Integer
torch.randint_like(my_tensor,0,10)

tensor([[0., 9., 0.],
        [9., 6., 9.]])

## Indexing and Slicing

In [32]:
x = torch.arange(6).reshape(3,-1)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [33]:
# Note: If you want to preserve the dimension, make sure to slice all the way through instead of indexing it
# Example:
# x[:,1] # returns (1,3)
x[:,1:] # returns (3,1)

tensor([[1],
        [3],
        [5]])

## View
Less operation overhead then reshape if tensor is contiguous in memory space.  
Basically,
```contiguous() + view() = reshape()```

*Note: Both view() and reshape() are linked to original tensor. Any further modification to the original tensor, gets reflected in the view/reshape assignment (z1 and z2 below)*

In [34]:
x.view(2,-1)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [35]:
x # Unchanged

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [36]:
z1 = x.view(2,-1)
z2 = x.reshape(2,-1)
print(z1)
print(z2)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [37]:
# Modifying x
x[0,0]  = -100
x

tensor([[-100,    1],
        [   2,    3],
        [   4,    5]])

In [38]:
z1 # Changes also reflected in view

tensor([[-100,    1,    2],
        [   3,    4,    5]])

In [39]:
z2 # Changes also reflected in reshape

tensor([[-100,    1,    2],
        [   3,    4,    5]])

## Math Operations
- These are element wise operations:
`+`
`-`
`*`
`/`

In [40]:
a = torch.randint(0,6,(3,2))
b = torch.randint_like(a,0,6)
print(a)
print()
print(b)

tensor([[1, 2],
        [2, 0],
        [2, 0]])

tensor([[2, 4],
        [0, 5],
        [3, 4]])


**Fun fact**  
 Underscore _ allows to do the following:  
 a = a + b  
 a.add_(b)

In [41]:
a.add_(b)

tensor([[3, 6],
        [2, 5],
        [5, 4]])

In [42]:
a

tensor([[3, 6],
        [2, 5],
        [5, 4]])

## Matrix Operations
These include:  
`@` matrix multiplication  
`a.dot(b)` sum of element-wise products  
`.T` Transpose 

In [43]:
z = a.T @ b
z

tensor([[21, 42],
        [24, 65]])

In [44]:
a.reshape(-1).dot(b.reshape(-1))

tensor(86)

## Advanced Matrix Operations

**Euclidean Norm**  
`.norm()`

In [45]:
s = z.reshape(-1).type(dtype=torch.float32)
s.norm()

tensor(83.7019)

**Number of Elements**  
`.numel()`

In [46]:
z.numel()

4