In [67]:
import torch
import numpy as np
np.random.seed(42)

In [68]:
arr = np.random.randint(0,10,10)
arr

array([6, 3, 7, 4, 6, 9, 2, 6, 7, 4])

**Convert numpy to tensor**

In [69]:
# torch.from_numpy(np_array)
t1 = torch.from_numpy(arr)
t1

tensor([6, 3, 7, 4, 6, 9, 2, 6, 7, 4], dtype=torch.int32)

In [70]:
# torch.as_tensor(np_array)
t1 = torch.as_tensor(arr)
t1

tensor([6, 3, 7, 4, 6, 9, 2, 6, 7, 4], dtype=torch.int32)

## 2D tensor

In [36]:
arr_2d = np.random.randint(0,10,12).reshape(4,-1)
t1_2d  = torch.as_tensor(arr_2d)
t1_2d

tensor([[6, 3, 8],
        [0, 7, 6],
        [1, 7, 0],
        [8, 8, 1]], dtype=torch.int32)

## **Copy**
Break link to original tensor, make a copy using
```torch.tensor()```

In [120]:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
my_tensor = torch.tensor(my_arr)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [122]:
my_other_tensor = torch.from_numpy(my_arr) # Actively shares memory with the original nparray
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [123]:
# Making changes to original nparray, reflects changes in copies and vice cersa
my_arr[0] = -1
my_other_tensor

tensor([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9], dtype=torch.int32)

In [124]:
# Making changes to copy of nparray, reflects changes back to original nparray
my_other_tensor[0] = 0
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
print(f"Original nparray: {my_arr}")
my_arr[0] = -1 # Making changes
print(f"Change to nparray: {my_arr}")
my_tensor # Copy of nparray as tensor, remains unaffected (No Linkage, Memory not shared)

Original nparray: [0 1 2 3 4 5 6 7 8 9]
Change to nparray: [-1  1  2  3  4  5  6  7  8  9]


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

## Difference in tensor and Tensor
Float Tensor => torch.Tensor() \
dynamic Tensor => torch.tensor()

*Note:* depends on the datatype of the original nparray passed as argument

In [128]:
my_arr = np.arange(0,1,0.1)
my_arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [133]:
torch.tensor(my_arr) # Infers the datatype of my_arr

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000], dtype=torch.float64)

In [134]:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
# t = torch.FloatTensor(my_arr)
t = torch.Tensor(my_arr) # Converts to float
print(t)
print(t.dtype)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.float32


## Initialize empty tensors
Place holder tensors with extremely small floating values \
```torch.empty(ndim,...)```

In [139]:
torch.empty(2,2)

tensor([[9.1477e-41, 1.8980e+01],
        [1.4013e-45, 0.0000e+00]])

In [148]:
torch.zeros(2,2, dtype=torch.int32)

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)